from database.studentDB import StudentDataBase
from domain.Student import Student
from operations.StudentController import StudentController
from UI.ui import UI
from database.disciplineDB import DisciplineDataBase
from domain.Discipline import Discipline
from operations.DisciplineController import DisciplineController
from database.gradeDB import GradeDataBase
from domain.Grade import Grade
from operations.GradeController import GradeController